from numba import njit
import numpy as np
import glm
import math
import random

@njit
def print_info(text):
    print(text)




#window resolution
WIN_RES = glm.vec2(1150, 700)

#background color
BG_COLOR = glm.vec3(0.0, 111 / 255,  222 / 255)


#sound
PLAYER_MAX_SOUND_DISTANCE = 20

#ray casting
MAX_RAY_DIST = 5


#camera
ASPECT_RATIO = WIN_RES.x / WIN_RES.y
FOV_DEG = 50
V_FOV = glm.radians(FOV_DEG)
H_FOV = 2 * math.atan(math.tan(V_FOV * 0.5) * ASPECT_RATIO)
NEAR = 0.075
FAR = 220.9
PITCH_MAX = glm.radians(89)


#chunk
CHUNK_SIZE = 32
CHUNK_H_SIZE = CHUNK_SIZE // 2
CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE
CHUNK_VOL = CHUNK_SIZE * CHUNK_AREA
CHUNK_SPHERE_RADIUS = CHUNK_SIZE * math.sqrt(3)



#world
WORLD_W, WORLD_H = 65, 7  
WORLD_D = WORLD_W 
WORLD_AREA = WORLD_D * WORLD_W
WORLD_VOL = WORLD_AREA * WORLD_H
SEED = 167

CENTER_X = (WORLD_W // 2) * CHUNK_SIZE
CENTER_Z = (WORLD_D // 2) * CHUNK_SIZE
WORLD_Y = WORLD_H * CHUNK_SIZE
CENTER_Y = WORLD_H * CHUNK_H_SIZE






#player
PLAYER_SPEED = 0.00399
PLAYER_SPRINT_SPEED = 0.00599
PLAYER_ROT_SPEED = 0.003
PLAYER_START_POS = glm.vec3((WORLD_W - 10) * CHUNK_SIZE, WORLD_Y , (WORLD_W - 10) * CHUNK_SIZE)
MOUSE_SENSITVITY = 0.002
PLAYER_HEIGHT = 2

#clouds 
SUNY = 0
CLOUDY = 1
RAIN = 2
THUNDERSTORM = 3

CLOUD_SCALE = 25
CLOUD_HEIGHT = WORLD_H * CHUNK_SIZE * 2



#entities
ENTITIES = ["chicken", ]
CHICKEN_SPEED = 0.1
CHINKEN_DEFAULT_HEALTH = 4
PLAYER_DEFAULT_HEALTH = 20
VELOCITY_PER_HP = 4


#effects
EFFECTS = ["wither", "poison", "regeneration"]



#chat 
MAX_TEXT_LENTGH = 50
TEXT_SIZE = 16
TEXT_POSITION = (0, int(WIN_RES.y - TEXT_SIZE))


#blocks
SAND = 1
GRASS = 2
DIRT = 3
STONE = 4
SNOW = 5
LEAVES = 6
WOOD = 7
BEDROCK = 8
COMMAND_BLOCK = 9
TORCH = 255
COAL_ORE = 10
YELLOW_WOOL = 11
BLUE_WOOL = 12
GLASS = 254
CRACKED_GASS_STONE = 13
DIAMOND_ORE = 14
WATER_FULL = 15
LIGHT_BLOCKS = [TORCH, ]

BLOCKS = [SAND, GRASS, DIRT, STONE, SNOW, LEAVES, WOOD, BEDROCK, COMMAND_BLOCK, 0, TORCH, COAL_ORE, YELLOW_WOOL, BLUE_WOOL, CRACKED_GASS_STONE, GLASS, DIAMOND_ORE, WATER_FULL]
BLOCK_NAMES = ["SAND", "GRASS", "DIRT", "STONE","SNOW", "LEAVES", "WOOD","BEDROCK", "COMMAND_BLOCK", "AIR", "TORCH", "COAL_ORE", "YELLOW_WOOL", "BLUE_WOOL","CRACKED_GASS_STONE","GLASS", "DIAMOND_ORE", "WATER_FULL"]



#items
COAL = 15


#hardness levels

HARDNESS_LEVELS  = {
    SAND : 14,
    GRASS : 10,
    DIRT : 10,
    STONE: 20,
    SNOW : 8,
    LEAVES: 3,
    WOOD : 10,
    BEDROCK : 0,
    COMMAND_BLOCK : 0,
    0 : 0,
    TORCH: 0,
    COAL_ORE: 28,
    YELLOW_WOOL: 15,
    BLUE_WOOL: 15,
    GLASS: 1,
    DIAMOND_ORE: 40,
    WATER_FULL :0,

}

#terrian generation
COAL_ORE_LEVEL_A = CHUNK_SIZE * 5
COAL_ORE_LEVEL_B = CHUNK_SIZE * 3

DIAMOND_ORE_LEVEL_A = CHUNK_SIZE * 2
DIAMOND_ORE_LEVEL_B = 8

SEA_LEVEL = 70


MOUNTIN_VARIABILITY = 4
MOUNTIN_MINUS = -(MOUNTIN_VARIABILITY // 2)
MOUNTIN_PLUS = -MOUNTIN_MINUS
MOUNTIN_LVL = 140

SNOW_VARIABILITY = 6
SNOW_MINUS = -(MOUNTIN_VARIABILITY // 2)
SNOW_PLUS = -SNOW_MINUS
SNOW_LVL = 4 * CHUNK_SIZE

TREE_MAX_HEIGHT = 10
TREE_MIN_HEIGHT = 5
TREE_MAX_WIDTH = 4
TREE_MIN_WIDTH = 3
TREE_PROPAB = 0.036
BUSH_HEIGHT = 2


CAVE_E_MIN = 5
CAVE_E_MAX = 35


#commands
DEFAULT_CMD_EXEC_POS =  glm.vec3(0, 0, 0)

#sun
SUN_RAD = WORLD_Y
START_SUN_ANGLE = 90
SUN_SPEED = 0.05
SUN_X = WORLD_W * CHUNK_H_SIZE

#biomes
DESERT = 0
PLAINS = 1
FOREST = 2
MOUNTIN_HOT = 3
SEA = 5
AFRICA_SAVANA = 6
MOUNTIN_COLD = 7

MOUNTIN_MIN_HEIGHT = 88
PLAIN_MIN_HEIGHT = 29
SEA_MIN_HEIGHT = 29


#debug
DEBUG_MODE = False

#gamemode
SURIVAL = 0
CREATIVE = 1
GAMEMODE = SURIVAL
NORMAL = 0
AVM = 1

TYPE = NORMAL

HARDCORE = 0


DIFFICULTY = 1

#frustum
PLAYER_CHUNK_FAR = FAR // CHUNK_SIZE

#light
LIGHT_DECREASE = 1
TORCH_LIGHT = 10




#save 
GENERATE = 0
LOAD = 1
GENERATE_OR_LOAD_WORLD = GENERATE